### PR TITLE
Updated 'xml-encryption' package to the latest version.

### PR DESCRIPTION
**Pull request by RopoMen**
- Fix security issue in https://github.com/advisories/GHSA-9pgh-qqpf-7wqj by updating package 'xml-encryption' to the latest version.

### CODE REVIEW

**Review by Rauttis — DISMISSED** [review]
Checked that tests pass

**Review by nnmn — DISMISSED** [review]

**Comment by Rauttis** [comment]
package-lock probably shouldn't be committed since this repo uses yarn

> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

**Comment by RopoMen** [comment]
> package-lock probably shouldn't be committed since this repo uses yarn
> 
> > warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

package-lock.json removed and added into `.gitignore`

**Review by annaruokonen — APPROVED** [review]

**Review by annaruokonen — DISMISSED** [review]
Looks good!

**Review by Rauttis — APPROVED** [review]

**Comment by Rauttis** [comment]
> > package-lock probably shouldn't be committed since this repo uses yarn
> > > warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> 
> package-lock.json removed and added into `.gitignore`

There should now be changes to yarn.lock file instead, but those are not committed

**Review by Rauttis — CHANGES_REQUESTED** [review]
yarn.lock file should be updated as well

**Review by Rauttis — APPROVED** [review]

**Review by nnmn — APPROVED** [review]

**Pull request merged**
