### PR TITLE
Upstream v1.3.5 merge

### PR DESCRIPTION
**Pull request by walokra**
Merge changes done in passport-saml until v1.3.5 tag.

### CODE REVIEW

**Comment by walokra** [comment]
The checks are failing because upstream yarn.lock has chalk@4.1.0 which expects node >=10. Chalk 4.10 comes from inquirer which comes from eslint 6.5.1.

Upstream has removed Travis CI build so I think they're not yet aware of the problem. Upstream supports oldest LTS release of Node (https://github.com/node-saml/passport-saml/releases/tag/v1.3.0) which is now Node 10 I think.

"error chalk@4.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.10.0""

**Comment by walokra** [comment]
Waiting for removing EOL Node 8 support in upstream: https://github.com/node-saml/passport-saml/pull/462

**Comment by tuomotalvitie** [comment]
[node-saml#462] seems to be merged, which is nice.

**Comment by walokra** [comment]
Merged the changes from 1.3.3-sfi.3 to this branch which fixes the blocking issues with Node 8 support in upstream.

Upstream has then moved to TypeScript (from v1.4.0 upwards) so for now didn't update the branch to v1.4.0 upstream.

**Comment by RopoMen** [comment]
I'll decline/close this PR. Gained benefit is not much (changes https://github.com/node-saml/passport-saml/releases/tag/v1.3.5). We are trying to get away from this fork and move to use upstream 'passport-saml' because it currently has almost all features which this fork has offered.

**Pull request closed without merging**
